import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";

import { AppContextProvider } from "@/context/AppContext";
import { CarContextProvider } from "@/context/CarContext";
import { FiltersContextProvider } from "@/context/FilterContext";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Barlow_Condensed } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { authOptions } from "./auth";
import "./globals.css";
import ReactQueryProvider from "./provider/ReactQueryProvider";
import Providers from "./provider/SessionProvider";

export const metadata: Metadata = {
  title: "Car Rental App",
  description: "Generated by create next app",
};
// font-family: 'Barlow Condensed', sans-serif;
const barlowCondensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
        className={`${barlowCondensed.className} w-full h-full m-0 p-0 overflow-x-hidden`}
      >
        <ReactQueryProvider>
          <Providers session={session}>
            <AppContextProvider>
              <CarContextProvider>
                <FiltersContextProvider>
                  <MantineProvider>
                    <NextTopLoader />
                    <main>{children}</main>
                  </MantineProvider>
                </FiltersContextProvider>
              </CarContextProvider>
            </AppContextProvider>
          </Providers>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
