import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Barlow_Condensed } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
import Providers from "./provider/sessionProvider";

export const metadata: Metadata = {
  title: "Car Rental App",
  description: "Generated by create next app",
};
// font-family: 'Barlow Condensed', sans-serif;
const barlowCondensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <Providers session={session}>
        <body
          className={`${barlowCondensed.className} w-full h-full m-0 p-0 overflow-x-hidden`}
        >
          <NextTopLoader />
          <main>{children}</main>
        </body>
      </Providers>
    </html>
  );
}
